### ISSUE TITLE
build automated testing for cell detector

### ISSUE THREAD

**Issue by outofculture** [acq4/acq4#237]
protocol:
1. find the surface
2. scan down 50µm
3. detect cells
4. allow user to evaluate its performance
5. repeat at a new location

**Comment by outofculture** [comment]
1. define a region to explore
2. hit the "Find a random target" button
3. it should result in a cell targeted. try to patch it?

**Comment by outofculture** [comment]
extra notes:
* set it to brightfield or fluorescence manually first
* test the single-frame and z-stack buttons as well, and notice whether one or the other is behaving better
* it's currently hard-coded to use "Pipette1"

**Comment by jessicatrnh** [comment]
- single frame is performing better for cell detection. works best in fluorescence.
- z-stack detection not working. 
- "Find a random target": moves to a random site, scans depth but does not select a random cell.

**Comment by outofculture** [comment]
okay, that should be working now

**Comment by jessicatrnh** [comment]
Neurons in z stack? still not working. Behavior: at current focus, scans ~20um depth (-10 to +10 um from current focus) and returns to midway point and returns to starting plane (current focus). Boxes not drawn after action is completed. 

Same behavior with finding random target.
Operator identifies top left and bottom right corners to restrict region. Objective scans to random region within set range. Scans -200 to +200 microns from current focal plane and returns to focal plane. No boxes drawn or target selected.
