### ISSUE TITLE
Problems running acq4 after install

### ISSUE THREAD

**Issue by JRS92** [acq4/acq4#258]
Hi,

I followed the installation instructions as described in the documentation, including a fresh install of anaconda. I cannot get acq4 to open after installing into a new python environment.

`(acq4) PS C:\Users\labpc\acq4> python -m acq4
Loading ACQ4...
===== 2024.06.26 16:06:20 =====
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\labpc\acq4\acq4\__main__.py", line 101, in <module>
    gc = GarbageCollector(interval=1.0, debug=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\labpc\AppData\Local\anaconda3\envs\acq4\Lib\site-packages\pyqtgraph\util\garbage_collector.py", line 28, in __init__
    self.timer.start(interval * 1000)
TypeError: arguments did not match any overloaded call:
  start(self, msec: int): argument 1 has unexpected type 'float'
  start(self): too many arguments
Can't log message; no log created yet.
{'exception': (<class 'TypeError'>, TypeError("arguments did not match any overloaded call:\n  start(self, msec: int): argument 1 has unexpected type 'float'\n  start(self): too many arguments"), <traceback object at 0x000001BD8F03A040>), 'msgType': 'error', 'threads': {}}`

**Comment by campagnola** [comment]
Hello,

The bug you are seeing was fixed several months ago in pyqtgraph; please be sure you are using a recent version of that package.
(see:https://github.com/pyqtgraph/pyqtgraph/commit/fb44444ff4acbccbc0b66011c008bf58adb23188)


Cheers,
Luke
________________________________
From: JRS92 ***@***.***>
Sent: Wednesday, June 26, 2024 13:58
To: acq4/acq4 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acq4/acq4] Problems running acq4 after install (Issue #258)


Hi,

I followed the installation instructions as described in the documentation, including a fresh install of anaconda. I cannot get acq4 to open after installing into a new python environment.

(acq4) PS C:\Users\labpc\acq4> python -m acq4 Loading ACQ4... ===== 2024.06.26 16:06:20 ===== Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "C:\Users\labpc\acq4\acq4\__main__.py", line 101, in <module> gc = GarbageCollector(interval=1.0, debug=False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\labpc\AppData\Local\anaconda3\envs\acq4\Lib\site-packages\pyqtgraph\util\garbage_collector.py", line 28, in __init__ self.timer.start(interval * 1000) TypeError: arguments did not match any overloaded call: start(self, msec: int): argument 1 has unexpected type 'float' start(self): too many arguments Can't log message; no log created yet. {'exception': (<class 'TypeError'>, TypeError("arguments did not match any overloaded call:\n start(self, msec: int): argument 1 has unexpected type 'float'\n start(self): too many arguments"), <traceback object at 0x000001BD8F03A040>), 'msgType': 'error', 'threads': {}}

**Comment by JRS92** [comment]
Thank you! I updated to the latest pyqtgraph and acq4 now opens. I am still getting error messages though, and I am not able to access Patch1.

`(acq4) PS C:\Users\labpc> python -m acq4
Loading ACQ4...
QMimeDatabase: Error loading internal MIME data
An error has been encountered at line 1 of <internal MIME data>: Premature end of document.:
============= Starting Manager configuration from c:\users\labpc\acq4\config\example\default.cfg =================
  === Configuring device 'DAQ' ===
Created NiDAQ handle, devices are ['Dev1']
  === Configuring device 'DaqDevice' ===
  === Configuring device 'Clamp1' ===
Error configuring device Clamp1:
c:\users\labpc\acq4\acq4\Manager.py:331: RuntimeWarning:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\labpc\acq4\acq4\__main__.py", line 104, in <module>
    man = Manager(argv=sys.argv[1:])
  File "c:\users\labpc\acq4\acq4\Manager.py", line 159, in __init__
    self.readConfig(configFile)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 245, in readConfig
    self.configure(self.config)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 284, in configure
    self._loadConfig(cfg)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 331, in _loadConfig
    printExc()
  --- exception caught here ---
  File "c:\users\labpc\acq4\acq4\Manager.py", line 325, in _loadConfig
    self.loadDevice(driverName, conf, k)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 462, in loadDevice
    dev = devclass(self, conf, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\labpc\acq4\acq4\devices\MockClamp\MockClamp.py", line 60, in __init__
    self.process = teleprox.ProcessSpawner(conda_env=config.get('condaEnv', None))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ProcessSpawner.__init__() got an unexpected keyword argument 'conda_env'
  printExc()
  === Configuring device 'RecordingChamber' ===
  === Configuring device 'Manipulator1' ===
  === Configuring device 'Pressure1' ===
  === Configuring device 'Pipette1' ===
  === Configuring device 'PatchPipette1' ===
  === Configuring device 'Stage' ===
  === Configuring device 'Microscope' ===
  === Configuring device 'Camera' ===
  === Configuring device 'Laser-UV' ===
  === Configuring device 'Scanner' ===
  === Configuring device 'PMT' ===
  === Configuring device 'PockelsCell' ===
=== Device configuration complete ===
=== Setting default HDF5 compression: None ===

============= Manager configuration complete =================

Loading module "Manager" as "Manager"...`

**Comment by JRS92** [comment]
I am not able to configure my PVCam camera in ACQ4, either.  I am getting error "'PVCam" object has no attribute 'cam'" on launch. I have the drivers installed and the camera working in other software. I am using the config listed in the examples with the serial of my camera.

**Comment by JRS92** [comment]
Hi Luke,

I am now pretty close to having our rig fully running acq4. I had to comment out some lines related to building the UI for the Patch module, and now it is working fine. I am now trying to get our microscope stage and manipulators (both Scientifica) working. Using the configuration for the Slicescope in the example config, I set the port to the correct number - our scope appears to use two, one for the condenser and one for the stage. I am now getting this on start:

`Loading ACQ4...
QMimeDatabase: Error loading internal MIME data
An error has been encountered at line 1 of <internal MIME data>: Premature end of document.:
============= Starting Manager configuration from c:\userslabpc\acq4\config\example\default.cfg =================
  === Configuring device 'DAQ' ===
Created NiDAQ handle, devices are ['Dev1', 'SimDev1']
  === Configuring device 'RecordingChamber' ===
  === Configuring device 'Manipulator1' ===
  === Configuring device 'Pressure1' ===
  === Configuring device 'Pipette1' ===
  === Configuring device 'Clamp1' ===
Created MultiClamp device model:MC700B,sn:00838628,chan:2
  === Configuring device 'SliceScope' ===
Error configuring device SliceScope:
c:\users\labpc\acq4\acq4\Manager.py:331: RuntimeWarning:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\labpc\acq4\acq4\__main__.py", line 104, in <module>
    man = Manager(argv=sys.argv[1:])
  File "c:\users\labpc\acq4\acq4\Manager.py", line 159, in __init__
    self.readConfig(configFile)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 245, in readConfig
    self.configure(self.config)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 284, in configure
    self._loadConfig(cfg)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 331, in _loadConfig
    printExc()
  --- exception caught here ---
  File "c:\users\labpc\acq4\acq4\devices\Scientifica\scientifica.py", line 38, in __init__
    self.dev = ScientificaDriver(port=port, name=name, baudrate=baudrate, ctrl_version=ctrl_version)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\labpc\acq4\acq4\drivers\Scientifica\scientifica.py", line 165, in __init__
    raise err
RuntimeError: Scientifica device b'SliceScope' uses controller version 3.7, but version 2 was requested. Warning: speed and acceleration parameter values are NOT compatible between controller versions.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "c:\users\labpc\acq4\acq4\Manager.py", line 325, in _loadConfig
    self.loadDevice(driverName, conf, k)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 462, in loadDevice
    dev = devclass(self, conf, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\labpc\acq4\acq4\devices\Scientifica\scientifica.py", line 41, in __init__
    raise RuntimeError(
RuntimeError: You must add `version=3` to the configuration for this device and double-check any speed/acceleration parameters.
  printExc()`

Where exactly should the controller version be specified? I tried adding "version: 3" to the devices configuration file under Slicescope but this caused it to not be detected at all. 

Thanks for your help!

**Comment by campagnola** [comment]
Adding version:3 should have been all you needed; let's figure out why the device wasn't detected at that point. Here's the SliceScope configuration from one of my rigs with a v3 scientifica controller:

SliceScope:
   driver: 'Scientifica'
   name: 'SliceScope'
   baudrate: 38400
   scale: -1e-6, 1e-6, -1e-6  # convert um to m
   version: 3
   slowSpeed: 100*um/s
   params:
       joyDirectionX: True
       joyDirectionY: False
       joyDirectionZ: True
       objDisp: -1500000
       objLift: 1500000

Notice that I have not specified the com port here, but rather the name of the device as assigned by linlab (acq4 will then try to automatically determine the com port). This is not required, though; you should be able to manually specify the com port too.

________________________________

**Comment by JRS92** [comment]
Hi Luke, I am not able to detect the scope using the name. The device is not found, and it tells me my options are : "[]" aka none. Weirdly, when I instead specify the com port, but not the version, I get "options are "b'SliceScope'"

 Weirdly, when I use the com port without specifying the version, it is able to tell me the device name is in fact "b'SliceScope'" and tell me that it uses controller version 3.7. When I specify the version, I then get a TypeError from Device line 65. self.name is type None and can't be concatenated with the string '_config'.

**Comment by JRS92** [comment]
Here are the error messages

```
Loading ACQ4...
QMimeDatabase: Error loading internal MIME data
An error has been encountered at line 1 of <internal MIME data>: Premature end of document.:
============= Starting Manager configuration from c:\users\labpc\acq4\config\example\default.cfg =================
  === Configuring device 'DAQ' ===
Created NiDAQ handle, devices are ['Dev1', 'SimDev1']
  === Configuring device 'Clamp1' ===
Created MultiClamp device model:MC700B,sn:00838628,chan:1
  === Configuring device 'SliceScope' ===
Error configuring device SliceScope:
c:\users\labpc\acq4\acq4\Manager.py:331: RuntimeWarning:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\labpc\acq4\acq4\__main__.py", line 104, in <module>
    man = Manager(argv=sys.argv[1:])
  File "c:\users\labpc\acq4\acq4\Manager.py", line 159, in __init__
    self.readConfig(configFile)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 245, in readConfig
    self.configure(self.config)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 284, in configure
    self._loadConfig(cfg)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 331, in _loadConfig
    printExc()
  --- exception caught here ---
  File "c:\users\labpc\acq4\acq4\Manager.py", line 325, in _loadConfig
    self.loadDevice(driverName, conf, k)
  File "c:\users\labpc\acq4\acq4\Manager.py", line 462, in loadDevice
    dev = devclass(self, conf, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\labpc\acq4\acq4\devices\Scientifica\scientifica.py", line 55, in __init__
    Stage.__init__(self, man, config, name)
  File "c:\users\labpc\acq4\acq4\devices\Stage\Stage.py", line 89, in __init__
    calibration = self.readConfigFile('calibration')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\labpc\acq4\acq4\devices\Device.py", line 76, in readConfigFile
    fileName = os.path.join(self.configPath(), filename)
                            ^^^^^^^^^^^^^^^^^
  File "c:\users\labpc\acq4\acq4\devices\Device.py", line 65, in configPath
    return os.path.join('devices', self.name() + '_config')
                                   ~~~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
  printExc()
=== Device configuration complete ===
=== Setting default HDF5 compression: None ===

============= Manager configuration complete =================

Loading module "Manager" as "Manager"...
```

**Comment by JRS92** [comment]
To update, it looks like the device ID I needed to use was PID:VID 10C4:EA70. This gets the scope recognized but in ACQ4 I get no update of position and the scope doesn't respond to movement commands

**Comment by JRS92** [comment]
The main issue seems to be that the scope + condenser and the two manipulators work via two serial ports on the control boxes that connect to the computer via one USB each. If the condenser is com8 and the scope (stage) is com7, then the condenser is detected as a new SliceScope and overwrites the first. My quick fix is to just skip over Com8; don't have much need to adjust the condenser with acq4 anyway. This is a bigger issue for the manipulators, though. Having two patchstars in the configuration file with different names (Left, Right etc. as in LinLab) seems to cause the same overwriting issue - only the manipulator with the higher COM number will work, the lower one will be overwritten.

**Comment by campagnola** [comment]
Thanks for being persistent on this! I will add the vendor/product IDs you found to the driver code. Given that we hadn't seen these IDs before, it seems likely that you have a newer version of their products, so we might expect to need some debugging before they work.

Regarding your condenser: if you use a motorized objective changer, then this is probably controlled via the condenser and you will definitely want both the condenser and the slicescope configured (as separate devices). If you don't have a motorized obective changer, then adding a microswitch connected to one of your digital input lines will allow acq4 to keep track of which objective you are using (highly recommended).

Can you say more about how one device "overwrites" another? We have rigs with 8 patchstars each, so I know in principle this should be able to work for you..

**Comment by campagnola** [comment]
I will test this soon: https://github.com/acq4/acq4/pull/261
